all: build test bench race

build:
	go build ./pkg/...

test:
	go test -v ./pkg/...

bench:
	go test -v -bench=. ./pkg/...

race:
	go test -v -race -coverprofile=coverage.txt -covermode=atomic ./pkg/...
